version: "3.8"
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules" # don't override folder inside container
      - "./:/app"
    ports:
      - "4000:4000"
